version: '3'

networks:
  backend:

services:
  app:
    container_name: rest-user
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment: 
      - MONGODB_URL=mongodb://mongo:27017/userdb
      - CLIENT_URL=${CLIENT_URL}
    links: 
      - mongo  
    depends_on:
      - mongo
    networks:
      - backend
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    networks:
      - backend